sudo: false
git:
  depth: 15
cache:
  pip: true
  directories:
  - /home/travis/Downloads/
 
language: python
python:
  - "3.6"
# Do not move from the root dir. requirements.txt is here
addons:
  chrome: stable
  apt:
    packages:
      - xvfb
before_install:
  - wget https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip -O temp.zip; unzip -o temp.zip -d $HOME/Downloads/
  - export PATH="$HOME/Downloads:$PATH"
  - Xvfb :99 -ac -screen 0 1280x1024x24 &
  - export DISPLAY=:99
  - nice -n 10 x11vnc 2>&1 &
script:
  - pytest --cov=surebet surebet/tests
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 98c1d7ba-04ce-4fd7-b487-9e8938227ef6
