sudo: required

git:
  depth: 15

language: python
cache:
  pip: true
  directories:
  - $HOME/Downloads

python:
  - "3.6"
# Do not move from the root dir. requirements.txt is here
addons:
  chrome: stable
  apt:
    packages:
      - xvfb
install:
  - pip install -r requirements.txt

  - python setup_driver.py
script:
  - pytest --cov=surebet surebet/tests

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 98c1d7ba-04ce-4fd7-b487-9e8938227ef6
